# Generated by Django 4.0.5 on 2022-06-12 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMarks',
            fields=[
                ('rollno', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('totalPercentage', models.FloatField()),
                ('mathMarks', models.IntegerField()),
                ('scienceMaths', models.IntegerField()),
                ('languageMarks', models.IntegerField()),
            ],
        ),
    ]
